<a href="https://colab.research.google.com/github/lovishdany/RL__NCU/blob/main/Lab-6__Policy_Iteration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math


grid=np.zeros((3,4))
grid[1,1] = math.inf
grid[0,3], grid[1,3] = 1, -1

operation_grid = np.array([["R","R","R",1],
                         ["U",0,"U",-1],
                         ["U","R","U","L"]])

g=0.9
reward_next=0
print(operation_grid)
print(grid)
old_grid=grid.copy()
new_grid=np.zeros((3,4))
grid_data=np.zeros((4,3,4))
grid_data
y=0
delta=1
while delta>0.3:
    # new_grid=grid_data[y].copy()
    diff_grid=new_grid.copy()
    for i in range(0,3):
        for j in range(0,4):
            if(operation_grid[i][j]=="R"):
                new_grid[i][j] = old_grid[i][j+1] + g*new_grid[i][j+1]
            elif(operation_grid[i][j]=="U"):
                new_grid[i][j] = old_grid[i-1][j] + g*new_grid[i-1][j]
            elif(operation_grid[i][j]=="L"):
                new_grid[i][j] = old_grid[i][j-1] + g*new_grid[i][j-1]
            else:
                continue
        # old_grid=new_grid.copy()
        # diff=np.array([])
    sub_grid=np.subtract(new_grid,diff_grid)
    delta=np.max(sub_grid)

    print()
    print(f"Iteration {y}")
    print(new_grid)
    print()
    print("Delta", delta)
    # new_grid_2= np.newaxis(new_grid)
    # grid_data=np.append(grid_data, new_grid, axis=0)
    y=y+1

[['R' 'R' 'R' '1']
 ['U' '0' 'U' '-1']
 ['U' 'R' 'U' 'L']]
[[ 0.  0.  0.  1.]
 [ 0. inf  0. -1.]
 [ 0.  0.  0.  0.]]

Iteration 0
[[0.    0.    1.    0.   ]
 [0.    0.    0.9   0.   ]
 [0.    0.    0.81  0.729]]

Delta 1.0

Iteration 1
[[0.    0.9   1.    0.   ]
 [0.    0.    0.9   0.   ]
 [0.    0.729 0.81  0.729]]

Delta 0.9

Iteration 2
[[0.81   0.9    1.     0.    ]
 [0.729  0.     0.9    0.    ]
 [0.6561 0.729  0.81   0.729 ]]

Delta 0.81

Iteration 3
[[0.81   0.9    1.     0.    ]
 [0.729  0.     0.9    0.    ]
 [0.6561 0.729  0.81   0.729 ]]

Delta 0.0


In [ ]:
operations = [[["R","D"],["L","R"],["L","R","D"],1],[["U","D"],0,["U","D","R"],-1],[["U","R"],["R","L"],["U","L","R"],["U","L"]]]
improve_grid=new_grid.copy()

for i in operations:
  print(i)
print()
print(improve_grid)





[['R', 'D'], ['L', 'R'], ['L', 'R', 'D'], 1]
[['U', 'D'], 0, ['U', 'D', 'R'], -1]
[['U', 'R'], ['R', 'L'], ['U', 'L', 'R'], ['U', 'L']]

[[0.81   0.9    1.     0.    ]
 [0.729  0.     0.9    0.    ]
 [0.6561 0.729  0.81   0.729 ]]


In [ ]:
for i in range(0,3):
  for j in range(0,4):
    store=[]
    for k in range(len(operations[i][j])):
      if(operation_grid[i][j][k]=="R"):
        p = old_grid[i][j+1] + g*new_grid[i][j+1]
        store.append(p)
      elif(operation_grid[i][j][k]=="U"):
        p = old_grid[i-1][j] + g*new_grid[i-1][j]
        store.append(p)
      elif(operation_grid[i][j][k]=="L"):
        p = old_grid[i][j-1] + g*new_grid[i][j-1]
        store.append(p)
      else:
        continue
    max = max(store)
    improve_grid[i][j]=max

print(imporve_grid)

IndexError: ignored